### PR TITLE
Adding basic ESP32 support

### PR DESCRIPTION
**Pull request by yurykk**
Based on Issue #71 (thanks @antonio-fiol).

Adding basic support for ESP32 (not including "examples").

### CODE REVIEW

**Comment by squix78** [comment]
Hi Yuri

Thank you so much for your PR! Just a few questions before I merge: 
* wouldn't it make sense to add our own Wifi header file which contains these compiler flags instead of adding them over and over again? (I wonder why the ESP32 coders did this change in the first place...
* What is the effect of the setNoDelay change?

**Comment by yurykk** [comment]
Hi

- I guess you are right ;-) adding own WiFi header. 
- Honestly, I didn't checked effect of setNoDelay by myself, just took it from @antonio-fiol suggested patch.   After playing with  both options, I see no noticeable effect. So, reverting it back to setNoDelay(false).
- Without "Ticker" support on ESP32 it looks a bit ugly (see WeatherStationDemo), still looking for better solution.

**Comment by antonio-fiol** [comment]
I was having trouble getting the info downloaded, and that was one of my
tests.
It turned out to be something else (checking if still connected made
everything fail) and forgot to roll back that.

**Comment by yurykk** [comment]
Please note that "WeatherStationDemoExtended" depends on the following : 

1) Experimental WiFiManager fork : https://github.com/bbx10/WiFiManager/tree/esp32

And the following libraries (are NOT supported by Espressif) : 

https://github.com/bbx10/WebServer_tng
https://github.com/bbx10/DNSServer_tng

**Pull request merged**
