### PR TITLE
Added APIs to retrieve current/forecast by coordinates (latitude/longitude) including examples

### PR DESCRIPTION
**Pull request by MarcFinns**
Fixes #\<GitHub-issue-number\>.

Make sure all boxes are checked (add x inside the brackets) when you submit your contribution, remove this sentence before doing so.

- [X] This PR is compliant with the [other contributing guidelines](https://github.com/ThingPulse/esp8266-weather-station/blob/master/CONTRIBUTING.md) as well (if not, please describe why).
- [X] I have thoroughly tested my contribution.
- [ ] Should this code require changes to documentation I will contribute those to [https://github.com/ThingPulse/docs](https://github.com/ThingPulse/docs).

\<Description of and rationale behind this PR\>

### CODE REVIEW

**Comment by marcelstoer** [comment]
Possible reason for build failures: ESP8266 Arduino-core disabled WPS by default with version 2.4.2. How to deal with this can be seen for example in https://github.com/switchdoclabs/OurWeatherWeatherPlus/pull/15

**Comment by MarcFinns** [comment]
Who ever talked about build failure..?

**Comment by MarcFinns** [comment]
I guess the original library does not compile either. None of my mods are wps related. I am aware of 2.4.2 issues. I am using the git version which has an auto detect mechanism. How do we proceed? Thanks

**Comment by marcelstoer** [comment]
I fixed the CI issues last night.

I like the inclusion of the coordinates, thanks. However, I'm not inclined to maintain separate examples for just this method. Rather I'd prefer to include a comment in the current OWM examples mentioning the coordinates (and location string) API e.g. https://github.com/ThingPulse/esp8266-weather-station/blob/master/examples/WeatherStationDemo/WeatherStationDemo.ino#L243 and https://github.com/ThingPulse/esp8266-weather-station/blob/master/examples/OpenWeatherMapCurrentDemo/OpenWeatherMapCurrentDemo.ino#L100

Could you adjust the PR accordingly please.

**Pull request closed without merging**
