### PR TITLE
fix: made compilable for ESP32 (#186, #190)

### LINKED ISSUE #186: ESP32 again
### Expected behavior
should compile

### Actual behavior
Compiling "WeatherStationDemo.ino"

```
C:\Arduino\libraries\ESP8266_Weather_Station\src\AerisForecasts.cpp: In member function 'void AerisForecasts::doUpdate(AerisForecastData*, String, uint8_t)':
C:\Arduino\libraries\ESP8266_Weather_Station\src\AerisForecasts.cpp:48:31: error: no matching function for call to 'WiFiClient::connect(const String&, const uint8_t&)'
   if(client.connect(host, port)) {
                               ^
```

What am I missing? 

I added this code to AerisObservations.cpp and AerisForecasts.cpp
```
typedef signed short        sint16_t;
typedef signed long         sint32_t;
```

Those Aeris-Files are not required for the standard Demo "WeatherStationDemo.ino". The "WiFiClient::connect"-error remains even after removing them.

Arduino-Version 1.8.13, latest and updated libraries and boards.
Any help please? 

### Weather Station version
master

### Hardware
D-Stike 32

### LINKED ISSUE #190: ESP32 error: 'AerisObservationsData has no member named 'tempC' and others
### Expected behavior

Compiling with esp32

### Actual behavior

Build crash with the next messages:

```C++
.pio/libdeps/m5stack-core-esp32/WeatherStation/src/AerisObservations.cpp: In member function 'virtual void AerisObservations::value(String)':
.pio/libdeps/m5stack-core-esp32/WeatherStation/src/AerisObservations.cpp:103:25: error: 'AerisObservationsData {aka struct AerisObservationsData}' has no member named 'tempC'
     this->observations->tempC = value.toInt();
                         ^
.pio/libdeps/m5stack-core-esp32/WeatherStation/src/AerisObservations.cpp:107:25: error: 'AerisObservationsData {aka struct AerisObservationsData}' has no member named 'tempF'
     this->observations->tempF = value.toInt();
                         ^
.pio/libdeps/m5stack-core-esp32/WeatherStation/src/AerisObservations.cpp:111:25: error: 'AerisObservationsData {aka struct AerisObservationsData}' has no member named 'dewpointC'
     this->observations->dewpointC = value.toInt();
                         ^
.pio/libdeps/m5stack-core-esp32/WeatherStation/src/AerisObservations.cpp:115:25: error: 'AerisObservationsData {aka struct AerisObservationsData}' has no member named 'dewpointF'
     this->observations->dewpointF = value.toInt();
                         ^
.pio/libdeps/m5stack-core-esp32/WeatherStation/src/AerisObservations.cpp:221:25: error: 'AerisObservationsData {aka struct AerisObservationsData}' has no member named 'heatindexC'
     this->observations->heatindexC = value.toInt();
                         ^
.pio/libdeps/m5stack-core-esp32/WeatherStation/src/AerisObservations.cpp:225:25: error: 'AerisObservationsData {aka struct AerisObservationsData}' has no member named 'heatindexF'
     this->observations->heatindexF = value.toInt();
                         ^
.pio/libdeps/m5stack-core-esp32/WeatherStation/src/AerisObservations.cpp:229:25: error: 'AerisObservationsData {aka struct AerisObservationsData}' has no member named 'windchillC'
     this->observations->windchillC = value.toInt();
                         ^
.pio/libdeps/m5stack-core-esp32/WeatherStation/src/AerisObservations.cpp:233:25: error: 'AerisObservationsData {aka struct AerisObservationsData}' has no member named 'windchillF'
     this->observations->windchillF = value.toInt();
                         ^
.pio/libdeps/m5stack-core-esp32/WeatherStation/src/AerisObservations.cpp:237:25: error: 'AerisObservationsData {aka struct AerisObservationsData}' has no member named 'feelslikeC'
     this->observations->feelslikeC = value.toInt();
                         ^
.pio/libdeps/m5stack-core-esp32/WeatherStation/src/AerisObservations.cpp:241:25: error: 'AerisObservationsData {aka struct AerisObservationsData}' has no member named 'feelslikeF'
     this->observations->feelslikeF = value.toInt();
                         ^
*** [.pio/build/m5stack-core-esp32/lib5c6/WeatherStation/AerisForecasts.cpp.o] Error 1
*** [.pio/build/m5stack-core-esp32/lib5c6/WeatherStation/AerisObservations.cpp.o] Error 1
.pio/libdeps/m5stack-core-esp32/WeatherStation/src/AerisSunMoon.cpp: In member function 'void AerisSunMoon::doUpdate(AerisSunMoonData*, String)':
.pio/libdeps/m5stack-core-esp32/WeatherStation/src/AerisSunMoon.cpp:47:31: error: no matching function for call to 'WiFiClient::connect(const String&, const uint8_t&)'
```

### Weather Station version
Current version on PlatformIO registry.

JsonStreamingParser Version: 1.0.5
WeatherStation Version: 2.0.1

### Hardware
Esp32 M5CoreInk

### PR DESCRIPTION
**Pull request by vlastahajek**
Closes #186, closes #190

- [X] This PR is compliant with the [other contributing guidelines](https://github.com/ThingPulse/esp8266-weather-station/blob/master/CONTRIBUTING.md) as well (if not, please describe why).
- [X] I have thoroughly tested my contribution.
- [X] Should this code require changes to documentation I will contribute those to [https://github.com/ThingPulse/docs](https://github.com/ThingPulse/docs).

Fixed compilation problems for ESP32.

### CODE REVIEW

**Comment by marcelstoer** [comment]
There's preliminary support for ESP32 in a dedicated branch: https://github.com/ThingPulse/esp8266-weather-station/compare/esp32

- everything compiles in CI
- none of the examples have actually been tested on hardware yet

**Comment by vlastahajek** [comment]
When do you plan to merge ESP32 support, please?

**Comment by marcelstoer** [comment]
Oh, good point, thanks. I just rebased the ESP32 branch. Still haven't tested on ESP32 hardware but I assume you did?

**Comment by vlastahajek** [comment]
Yes, I'm using forecast and current weather API and it works in general.

**Pull request closed without merging**
